
EMPLOYEE REPORT
EMPLOYEE PRL & RETIREMENT INFORMATION
RELIGION WISE EMPLOYEE SUMMARY
EMPLOYEE PROFILE
CLASS WISE EMPLOYEE SUMMARY REPORT
DEPARTMENT WISE GRADE POST REPORT
গ্রেডওয়াইজ অনুমোদিত পদ ও গ্রেড ওয়াইজ বিদ্যমান জনবলের বিবরণ
EMPLOYEE TRANSFER DETAILS
EMPLOYEE DETAILS INFORMATION
DEPARTMENT WISE DAILY ATTENDANCE SUMMARY
অনুমোদিত, বিদ্যমান ও শূন্য পদের বিবরণ
কর্মরত জনবলের লিঙ্গভিত্তিক বিভাজন
কর্মরত মুক্তিযোদ্ধা কর্মচারীদের বিবরণ
EMPLOYEE PUNISHMENT DETAILS
নিরাপত্তা বিভাগে কর্মরত কর্মকর্তাদের টেলিফোন ইনডেক্স
যুগ্মসচিব ও তদুর্ধ্ব পদমর্যাদার কর্মকর্তাগণের নামের তালিকা
EMPLOYEE TOUR INFORMATION DETAILS
STATISTICS OF CIVIL OFFICERS AND STAFF
মন্ত্রণালয় অথবা বিভাগ সমূহের মাসিক প্রতিবেদন ছক
EMPLOYEE PROMOTION REPORT
TIME SCALE REPORT
EMPLOYEE TELEPHONE INDEX
FREEDOM FIGHTER CHILDREN AND GRANDCHILDREN
TRAINED PROMOTION REPORT
DEPARTMENT WISE INCREMENT REPORT
DEPARTMENT AND DESIGNATION WISE SANCTION POST SUMMARY
DEPARTMENT WISE EMPLOYEE SUMMARY
DESIGNATION WISE SANCTION POST SUMMARY
DEPARTMENT WISE SANCTION POST SUMMARY
GRADE WISE SANCTION POST SUMMARY

#__BVID__22 > div > select > option:nth-child(8)

/html/body/div[2]/div[3]/div[2]/div[2]/section/div/div/div/div/div/div/div/select/option[8]

<option value=
EMPLOYEE TRANSFER DETAILS</option>


EMPLOYEE REPORT
EMPLOYEE PRL & RETIREMENT INFORMATION
RELIGION WISE EMPLOYEE SUMMARY
EMPLOYEE PROFILE
CLASS WISE EMPLOYEE SUMMARY REPORT
DEPARTMENT WISE GRADE POST REPORT
গ্রেডওয়াইজ অনুমোদিত পদ ও গ্রেড ওয়াইজ বিদ্যমান জনবলের বিবরণ
EMPLOYEE TRANSFER DETAILS
EMPLOYEE DETAILS INFORMATION
DEPARTMENT WISE DAILY ATTENDANCE SUMMARY
অনুমোদিত, বিদ্যমান ও শূন্য পদের বিবরণ
কর্মরত জনবলের লিঙ্গভিত্তিক বিভাজন
কর্মরত মুক্তিযোদ্ধা কর্মচারীদের বিবরণ
EMPLOYEE PUNISHMENT DETAILS
নিরাপত্তা বিভাগে কর্মরত কর্মকর্তাদের টেলিফোন ইনডেক্স
যুগ্মসচিব ও তদুর্ধ্ব পদমর্যাদার কর্মকর্তাগণের নামের তালিকা
EMPLOYEE TOUR INFORMATION DETAILS
STATISTICS OF CIVIL OFFICERS AND STAFF
মন্ত্রণালয় অথবা বিভাগ সমূহের মাসিক প্রতিবেদন ছক
EMPLOYEE PROMOTION REPORT
TIME SCALE REPORT
EMPLOYEE TELEPHONE INDEX
FREEDOM FIGHTER CHILDREN AND GRANDCHILDREN
TRAINED PROMOTION REPORT
DEPARTMENT WISE INCREMENT REPORT
DEPARTMENT AND DESIGNATION WISE SANCTION POST SUMMARY
DEPARTMENT WISE EMPLOYEE SUMMARY
DESIGNATION WISE SANCTION POST SUMMARY
DEPARTMENT WISE SANCTION POST SUMMARY
GRADE WISE SANCTION POST SUMMARY</option></select>